spring:
  application:
    name: DevForge
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/DevForge
provisioner:
  url: ${PROVISIONER_URL:http://localhost:8081}
server:
  servlet:
    context-path: /api/v1


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true
  api-docs:
    path: /v3/api-docs


keycloak:
  server-url: http://localhost:8180
  realm: DevForge
  adminClientId: devforge-admin
  adminClientSecret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}